### ISSUE TITLE
Neither Type 1 nor Type 2 errors are explained

### ISSUE THREAD

**Issue by bronwencc** [learn-co-curriculum/dsc-2-20-10-type-1-and-type-2-errors#1]
There is no explicit statement in this lesson explaining what Type 1 and Type 2 errors are.  The only direct mention of them is "These two errors have a direct relation to each other; reducing type 1 errors will increase type 2 errors and vice versa," which appears to be out of context.

**Comment by fpolchow** [comment]
added examples of type 1 and type 2 errors in real-world scenarios as well as theoretical explanations
