### ISSUE TITLE
is this for variance or standard deviation?

### ISSUE THREAD

**Issue by mgavish** [learn-co-curriculum/dsc-2-20-10-type-1-and-type-2-errors#3]
The variance of a binomial distribution is given by:

`σ=n∙p∙(1−p)⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯√σ=n∙p∙(1−p)`

**Comment by fpolchow** [comment]
You are correct! all fixed now. Thanks for flagging
